### ISSUE TITLE
MercuryTrade randomly stops opening notifications

### ISSUE THREAD

**Issue by TaigaTenori** [Exslims/MercuryTrade#220]
This has been happening for a good while, so I've opened it through the console.

Here is the output while notifications don't pop up.

```
`C:\Users\Peter>java -jar C:\Users\Peter\Documents\Takietam\PoE\MercuryTrade\MercuryTrade.jar

JNativeHook: Global keyboard and mouse hooking for Java.
Copyright (C) 2006-2015 Alexander Barker.  All Rights Received.
https://github.com/kwhat/jnativehook/

JNativeHook is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

JNativeHook is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
02:14:49.221 [Thread-7] ERROR ErrorHandler - rx.exceptions.OnErrorNotImplementedException
        at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
        at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
        at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
        at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
        at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
        at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216)
        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
        at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
        at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
        at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
        at com.mercury.platform.core.utils.interceptor.PlainMessageInterceptor.process(PlainMessageInterceptor.java:34)
        at com.mercury.platform.core.utils.interceptor.MessageInterceptor.match(MessageInterceptor.java:17)
        at com.mercury.platform.core.utils.MessageFileHandler.lambda$null$2(MessageFileHandler.java:86)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.mercury.platform.core.utils.MessageFileHandler.lambda$parse$3(MessageFileHandler.java:85)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.mercury.platform.core.utils.MessageFileHandler.parse(MessageFileHandler.java:84)
        at com.mercury.platform.core.utils.FileMonitor$1.onFileChange(FileMonitor.java:43)
        at org.apache.commons.io.monitor.FileAlterationObserver.doMatch(FileAlterationObserver.java:410)
        at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:333)
        at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:303)
        at org.apache.commons.io.monitor.FileAlterationMonitor.run(FileAlterationMonitor.java:182)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.mercury.platform.ui.components.panel.notification.TradeOutNotificationPanel.lambda$subscribe$6(TradeOutNotificationPanel.java:81)
        at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
        ... 16 more

`

```

**Comment by jannisg** [comment]
Just trying to figure out if this is the same issue as mine, when the notifications don't show up, can you use the "Unlock UI" button for the placeholder of the notifications panel to show up and move the placeholder? Once locked my notifications are showing again.

Weird but can't figure out why this is happening and trying to avoid a duplicate ticket if yours is also reacting this way.
