### ISSUE TITLE
POE loses focus occasionally when MercuryTrade is running in the background.

### ISSUE THREAD

**Issue by EllYouSeeKay** [Exslims/MercuryTrade#49]
Win 10, POE running in windowed borderless.

Every 5 minutes or so the windows taskbar becomes focused on top of the POE client.  Issue doesn't occur when MercuryTrade is not running.

**Comment by Exslims** [comment]
Pretty rare problem, if you can catch the moment because of what is happening(mouse over on something etc) then write it up please

**Comment by EllYouSeeKay** [comment]
Will do.  I can't find anything consistent yet.

**Comment by KatNDusty** [comment]
Same thing happens to me as well. So far as i can tell the only fix is to make the taskbar auto hide.. but I have no want to do that.. Would anybody else have a fix.. Mine seems more constant... It loses focus every few seconds and places the Windows 10 taskbar above the poe client.

**Comment by KatNDusty** [comment]
Haven't done all that much digging or anything but It may have something to do with Java. No fix I've found yet.

**Comment by Exslims** [comment]
okay, please provide app.log file from %userprofile%/appdata/local/MercuryTrade folder

**Comment by EllYouSeeKay** [comment]
[app.log.txt](https://github.com/Exslims/MercuryTrade/files/873639/app.log.txt)

Just let me know if you want me to delete the contents and leave the link.

2017-03-23 23:28:22.604 [nioEventLoopGroup-2-1] DEBUG UpdaterClient - Connection established
2017-03-23 23:28:22.606 [nioEventLoopGroup-2-1] INFO  ClientHandler - Requesting update info from server
2017-03-23 23:30:36.651 [AWT-EventQueue-0] INFO  GamePathChooser - UI module was started.
2017-03-24 00:00:58.759 [AWT-EventQueue-0] ERROR ErrorHandler - java.lang.NullPointerException
2017-03-24 00:00:58.760 [AWT-EventQueue-0] ERROR com.mercury.platform.shared.ConfigManager - Error during adding message to history file: 
java.lang.NullPointerException: null
	at com.mercury.platform.shared.HistoryManager.add(HistoryManager.java:75) ~[MercuryTrade.jar:?]
	at com.mercury.platform.ui.frame.impl.HistoryFrame.lambda$null$57(HistoryFrame.java:121) ~[MercuryTrade.jar:?]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_73]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_73]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_73]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_73]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_73]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_73]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_73]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_73]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_73]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_73]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_73]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_73]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_73]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_73]
2017-03-24 00:00:58.769 [AWT-EventQueue-0] ERROR ErrorHandler - java.lang.NullPointerException
2017-03-24 00:01:01.611 [AWT-EventQueue-0] ERROR ErrorHandler - java.util.MissingFormatArgumentException: Format specifier '%s'
2017-03-24 00:45:27.571 [AWT-EventQueue-0] ERROR ErrorHandler - java.lang.NullPointerException
2017-03-24 00:45:27.572 [AWT-EventQueue-0] ERROR com.mercury.platform.shared.ConfigManager - Error during adding message to history file: 
java.lang.NullPointerException: null
	at com.mercury.platform.shared.HistoryManager.add(HistoryManager.java:75) ~[MercuryTrade.jar:?]
	at com.mercury.platform.ui.frame.impl.HistoryFrame.lambda$null$57(HistoryFrame.java:121) ~[MercuryTrade.jar:?]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_73]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_73]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_73]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_73]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_73]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_73]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_73]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_73]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_73]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_73]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_73]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_73]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_73]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_73]
2017-03-24 00:45:27.573 [AWT-EventQueue-0] ERROR ErrorHandler - java.lang.NullPointerException
2017-03-24 00:45:31.194 [AWT-EventQueue-0] ERROR ErrorHandler - java.util.MissingFormatArgumentException: Format specifier '%s'
2017-03-24 03:28:34.834 [nioEventLoopGroup-2-1] ERROR ClientHandler - java.io.IOException: An existing connection was forcibly closed by the remote host
2017-03-24 03:28:34.835 [nioEventLoopGroup-2-1] DEBUG UpdaterClient - Connection lost
2017-03-24 03:28:34.839 [nioEventLoopGroup-2-1] INFO  ClientHandler - Channel is inactive
2017-03-24 09:43:47.418 [nioEventLoopGroup-2-2] DEBUG UpdaterClient - Connection established
2017-03-24 09:43:47.419 [nioEventLoopGroup-2-2] INFO  ClientHandler - Requesting update info from server
2017-03-24 09:58:23.735 [nioEventLoopGroup-2-2] ERROR ClientHandler - java.io.IOException: An existing connection was forcibly closed by the remote host
2017-03-24 09:58:23.735 [nioEventLoopGroup-2-2] DEBUG UpdaterClient - Connection lost
2017-03-24 09:58:23.736 [nioEventLoopGroup-2-2] INFO  ClientHandler - Channel is inactive
2017-03-24 10:01:44.955 [nioEventLoopGroup-2-4] DEBUG UpdaterClient - Connection established
2017-03-24 10:01:44.956 [nioEventLoopGroup-2-4] INFO  ClientHandler - Requesting update info from server
2017-03-25 21:49:32.747 [nioEventLoopGroup-2-4] DEBUG UpdaterClient - Connection lost
2017-03-25 21:49:32.766 [nioEventLoopGroup-2-4] INFO  ClientHandler - Channel is inactive
2017-03-26 11:27:01.300 [nioEventLoopGroup-2-1] DEBUG UpdaterClient - Connection established
2017-03-26 11:27:01.303 [nioEventLoopGroup-2-1] INFO  ClientHandler - Requesting update info from server
2017-03-27 01:27:13.914 [nioEventLoopGroup-2-1] ERROR ClientHandler - java.io.IOException: An existing connection was forcibly closed by the remote host
2017-03-27 01:27:13.918 [nioEventLoopGroup-2-1] DEBUG UpdaterClient - Connection lost
2017-03-27 01:27:13.928 [nioEventLoopGroup-2-1] INFO  ClientHandler - Channel is inactive
2017-03-27 06:28:44.423 [nioEventLoopGroup-2-12] DEBUG UpdaterClient - Connection established
2017-03-27 06:28:44.424 [nioEventLoopGroup-2-12] INFO  ClientHandler - Requesting update info from server
2017-03-27 09:30:38.670 [nioEventLoopGroup-2-12] DEBUG UpdaterClient - Connection lost
2017-03-27 09:30:38.689 [nioEventLoopGroup-2-12] INFO  ClientHandler - Channel is inactive
2017-03-27 11:39:04.597 [nioEventLoopGroup-2-1] DEBUG UpdaterClient - Connection established
2017-03-27 11:39:04.601 [nioEventLoopGroup-2-1] INFO  ClientHandler - Requesting update info from server

**Comment by KatNDusty** [comment]
2017-03-27 04:58:34.267 [AWT-EventQueue-0] INFO  GamePathChooser - UI module was started.
2017-03-27 05:15:47.381 [AWT-EventQueue-0] ERROR ErrorHandler - java.lang.NullPointerException
2017-03-27 05:15:47.383 [AWT-EventQueue-0] ERROR com.mercury.platform.shared.ConfigManager - Error during adding message to history file: 
java.lang.NullPointerException: null
	at com.mercury.platform.shared.HistoryManager.add(HistoryManager.java:75) ~[MercuryTrade.jar:?]
	at com.mercury.platform.ui.frame.impl.HistoryFrame.lambda$null$57(HistoryFrame.java:121) ~[MercuryTrade.jar:?]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_121]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_121]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_121]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_121]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_121]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_121]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_121]
2017-03-27 05:15:47.388 [AWT-EventQueue-0] ERROR ErrorHandler - java.lang.NullPointerException
2017-03-27 05:16:01.801 [AWT-EventQueue-0] ERROR ErrorHandler - java.util.MissingFormatArgumentException: Format specifier '%s'

**Comment by KatNDusty** [comment]
Sorry wouldnt let me upload the .txt for some odd reason

**Comment by etofok** [comment]
you can try the exe launcher we have (don't forget to run it as admin)

**Comment by Exslims** [comment]
hm, I see that there are errors which are corrected in the next version, but could you make hard reset and see whether taskbar still appears.
hard reset = delete MercuryTrade folder from  %userprofile%/appdata/local

**Comment by KatNDusty** [comment]
I clicked "run as administrator" on the exe launcher and nothing appeared to happen. I checked my processes and sure enough it was there.. but It wouldn't "run" until i actually ran the jar.

**Comment by KatNDusty** [comment]
Hard reset had no effect unfortunately

**Comment by Exslims** [comment]
there are any errors in the app.log file?

**Comment by EllYouSeeKay** [comment]
Can do.  I'll report back shortly.

**Comment by KatNDusty** [comment]
2017-03-27 13:22:42.333 [nioEventLoopGroup-2-1] DEBUG UpdaterClient - Connection established
2017-03-27 13:22:42.334 [nioEventLoopGroup-2-1] INFO  ClientHandler - Requesting update info from server
2017-03-27 13:23:03.126 [AWT-EventQueue-0] INFO  GamePathChooser - UI module was started.
2017-03-27 13:25:14.943 [nioEventLoopGroup-2-1] DEBUG UpdaterClient - Connection lost
2017-03-27 13:25:14.945 [nioEventLoopGroup-2-1] INFO  ClientHandler - Channel is inactive
2017-03-27 13:31:38.967 [nioEventLoopGroup-2-1] DEBUG UpdaterClient - Connection established
2017-03-27 13:31:38.969 [nioEventLoopGroup-2-1] INFO  ClientHandler - Requesting update info from server
2017-03-27 13:33:08.961 [nioEventLoopGroup-2-1] DEBUG UpdaterClient - Connection lost
2017-03-27 13:33:08.965 [nioEventLoopGroup-2-1] INFO  ClientHandler - Channel is inactive
2017-03-27 13:35:00.422 [nioEventLoopGroup-2-1] DEBUG UpdaterClient - Connection established
2017-03-27 13:35:00.422 [nioEventLoopGroup-2-1] INFO  ClientHandler - Requesting update info from server
2017-03-27 13:35:02.072 [nioEventLoopGroup-2-1] DEBUG UpdaterClient - Connection lost
2017-03-27 13:35:02.076 [nioEventLoopGroup-2-1] INFO  ClientHandler - Channel is inactive
2017-03-27 13:35:16.691 [nioEventLoopGroup-2-1] DEBUG UpdaterClient - Connection established
2017-03-27 13:35:16.693 [nioEventLoopGroup-2-1] INFO  ClientHandler - Requesting update info from server
2017-03-27 13:36:13.450 [nioEventLoopGroup-2-1] DEBUG UpdaterClient - Connection lost
2017-03-27 13:36:13.454 [nioEventLoopGroup-2-1] INFO  ClientHandler - Channel is inactive

**Comment by KatNDusty** [comment]
Im heading to work, Ill be back on in 4 hours. Ill try to keep in contact on my phone in the meantime... But i willl not be at my PC. Feel free to leave questions in the thread here! Thanks!

**Comment by EllYouSeeKay** [comment]
Just occurred again after the hard reset.  If the log file is up to date, it doesn't look like there is an error when this happens.  Let me know if there is anything else I can do to help debug.

__
2017-03-27 13:28:48.129 [nioEventLoopGroup-2-1] DEBUG UpdaterClient - Connection established
2017-03-27 13:28:48.131 [nioEventLoopGroup-2-1] INFO  ClientHandler - Requesting update info from server
2017-03-27 13:30:31.377 [AWT-EventQueue-0] INFO  GamePathChooser - UI module was started.
2017-03-27 13:54:13.333 [nioEventLoopGroup-2-1] DEBUG UpdaterClient - Connection lost
2017-03-27 13:54:13.339 [nioEventLoopGroup-2-1] INFO  ClientHandler - Channel is inactive
2017-03-27 13:54:22.552 [nioEventLoopGroup-2-2] DEBUG UpdaterClient - Connection established
2017-03-27 13:54:22.553 [nioEventLoopGroup-2-2] INFO  ClientHandler - Requesting update info from server

**Comment by Exslims** [comment]
found someone who had the same problem:

> I found out what was causing window's taskbar to popup time to time on windows 10 64bit. It's was due to slideshow wallpaper setting.

**Comment by EllYouSeeKay** [comment]
Interesting.  Do you think that's something that can be worked around within Mercury Trade?  Or is it more of a 'won't fix' due to the ease with which users can solve the issue?  I'll disable my slideshow and see if that takes care of it.

**Comment by Exslims** [comment]
i think its a java platform problem with win10, maybe not, I haven't researched this issue for a long time.

**Comment by EllYouSeeKay** [comment]
It seems like disabling the slideshow does fix the focus issue.

**Comment by KatNDusty** [comment]
No workaround for the slideshow disable?
