### ISSUE TITLE
Mercury Trade disapears

### ISSUE THREAD

**Issue by Hejtero** [Exslims/MercuryTrade#78]
So like yesterday or 2 days ago my Mecury Trade started to desapear, i mean i hear the trade sound but pannel just isnt there, i can click then on my  system bar to "restore default icon" but still then it desapear after any alt tab or so. 

Also it needs a lot more time to load when i start the program.

I tryed both launchers and so, sometimes the messages pop up and shows the messages even from like 2h ago. Also its seems laggy as hell. When i run it after deleting all in appdata the clicks occured like 10 sec late and so lol

**Comment by Exslims** [comment]
I made some changes and hope they will help to solve this problem in next update

**Comment by Hejtero** [comment]
thanks, when we can expect it?

**Comment by Exslims** [comment]
about 2-3h

**Comment by ryhmaeoamk** [comment]
The issue still persists after the update.
The problem I'm having is that the MercuryTrade notification bar and notifications are visible but they are  behind the poe main window. This usually happens after alt+tabbing and seems to be worse after the update.
When you set the game to windowed mode and move the window you can see the mercurytrade panels behind the game on desktop.

**Comment by ryhmaeoamk** [comment]
Has not happened with dx9ex so far. I was using dx11.

EDIT: Happened with dx9ex as well.

**Comment by slicplaya** [comment]
I'm using dx9ex as well i've tried numerous options. Deleted history, fresh install. It just started happening randomly one day, and I have to do the exact same thing restart restore to default to get it to pop up in game. It still hides behind poe screen after alt tabbing.

**Comment by MasonTallis** [comment]
Happening for me as well. Started in the .12 update, kept on when I rolled back to .11, still persistent. 

Behavior is as stated above, app restart combined with PoE restart are all that fixes it. Might need some special compatibility to work with alt-tabbing/borderless windowed. Looks like it's still being drawn, but it's not being drawn as an overlay (always on top) of the expected window.

**Comment by Exslims** [comment]
guys, have you tried .exe as admin?

**Comment by MasonTallis** [comment]
Where is there an .exe? All I see in releases are .jar files, which Windows' context menu does not support run-as-admin for. 

E: Nvm, found it. Will report back.
E2: This seems to work. I was able to force the exe to not work when not run as admin, and the jar, but not admin executable. Might be the way to go for now.

**Comment by Hejtero** [comment]
The update didn't change anything for me, still don't work :S. It still is laggy, click takes few sec to trigger and it still disapear after alt tab :( . MasonTallis can you explaing step by step what did you do to make it work?

**Comment by MasonTallis** [comment]
I just downloaded the rar archive, extracted everything (to the same place obv.), and ran the executable as admin.

**Comment by Hejtero** [comment]
Than i did try this before and it dont work T_T. So hard to trade without Mercury when i got used to it

**Comment by Exslims** [comment]
you tried .exe as **admin**? and it didn't work?

**Comment by slicplaya** [comment]
Are you talking about Java being the .exe? Cuz i only find the executable jar file 
It doesn't allow me to change my permissions on an executable file

**Comment by slicplaya** [comment]
Yea found the .exe, did a fresh install and had it run as administrator only. It still runs correctly, but once u alt tab and go back the overlay doesn't show above the game. Looks like no more Mercury trade for me. I'll still use it in background for the sound tho.

**Comment by Hejtero** [comment]
i have the same problem as slicplaya + mercury trade lags, it takes a while to run and then clicks are sent with like 5 sec delay

**Comment by Exslims** [comment]
could you provide this information:
1. Your OS
2. Steam/Standalone client
3. when and what version the last time it worked correctly
Thanks

**Comment by slicplaya** [comment]
Windows 8.1(eww)
Standalone
1.0.1

**Comment by Exslims** [comment]
and as I understand it the problem appeared suddenly and the updates have nothing to do with?

**Comment by Exslims** [comment]
@slicplaya and even on this version(1.0.1 or 1.0.0.*) of mercury does not work now?

**Comment by slicplaya** [comment]
lemme delete everything again n try older version

**Comment by Exslims** [comment]
ye, u can reset application by deleting MercuryTrade folder from %userprofile%/appdata/local

**Comment by Hejtero** [comment]
i did try the first versioni downloaded some time ago and it don't work. i got windows 7 proffesional 64 bit
standalone

**Comment by Exslims** [comment]
it looks very weird, did you try re-install java maybe?

**Comment by slicplaya** [comment]
I just tried 1.0.0.0, reinstalled java the master everything. It works perfect, but as soon as I alt+tab n go back. the overlay disappears and is put in the background under the game no matter what.

**Comment by Exslims** [comment]
try to run the game not from the administrator and mercury(.exe) from the administrator please.

**Comment by slicplaya** [comment]
I never run poe as admin so that's covered

**Comment by Exslims** [comment]
in app.log file alter alt+tab something appeared?

**Comment by slicplaya** [comment]
Everything works correctly. The problem is the overlay goes underneath the game screen once you alt+tab off the game even once. At that point you cannot see it anymore unless u change the resolution and move the game windowed, restore default location, or restarting it. Still makes the sounds and everything.

**Comment by Exslims** [comment]
so, your game in windowed fullscreen right now? its doesn't work in fullscreen.

**Comment by Exslims** [comment]
ok, i made some changes and please download MercuryTrade.jar from this link and try again.
[https://github.com/Exslims/MercuryTrade/releases/tag/1.0.1.3a](https://github.com/Exslims/MercuryTrade/releases/tag/1.0.1.3a)

**Comment by Hejtero** [comment]
seems like it now stays on top if i replace the jar and use exe as admin but need to test it little longer

**Comment by Hejtero** [comment]
its still like laggy, i hear the song then the trade window pop up like 15sec later and the Item Grid option sometimes dont even show up ;s but its useable now at least

**Comment by cokoboko1** [comment]
I would like to report that the problem described happened to AHK Macros too reported here https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/311

**Comment by Hejtero** [comment]
poe trade macro works ok as usuall for me, mercury started to work also but as i stated before its laggy, the trade window shows way to late, i usually hear the sound and invite manually, then windows usually shows mid trade, sometimes it shows faster sometimes slower

**Comment by Exslims** [comment]
Hi, could you provide app.log file from %userprofile%/appdata/local/MercuryTrade

**Comment by Exslims** [comment]
i updated last .jar, could you try this
[https://github.com/Exslims/MercuryTrade/releases/tag/1.0.1.3a](https://github.com/Exslims/MercuryTrade/releases/tag/1.0.1.3a)

**Comment by Hejtero** [comment]
nothing changed for me with the new jar (btw if im trying to use the jar to run mercury layout don't even show up) with the exe layout is there but still sometimes work ok and sometimes window pop up in like middle of the trade

**Comment by Exslims** [comment]
@Hejtero buttons works ok?

**Comment by Hejtero** [comment]
not rly :(  the panel seems to freeze from time to time and thats the  reason that i hear the sound but window dont pop up. When i click on the pannel after hearing the sound it seems freezed but after few sec it unfreeze and then window imediatelly pop up. I don't know why it works like that lol, when i was watching a movie with PoE in background every time someone wanted to trade the window pop up normally, 0 freezes but if im browsing poe trade or playing the game, it freezes somehow and becouse of this window pop up with few seconds delay

**Comment by LehMarc** [comment]
The question may be a bit funny, but do you use RivaTuner? I had a problem with MT (Mercury Trade) after installed the Creators Update for Win 10. Double clicked the .exe file, nothing happened. I then found out that the program RivaTuner caused problems. Deleted RivaTuner (MSI Afterburner) - MT works again :)

From the logfile:


 A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffa5514fd0c, pid=10828, tid=0x000000000000366c

 JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode windows-amd64 compressed oops)
 Problematic frame:
 C  [d3d9.dll+0xfd0c]

 Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

**Comment by Exslims** [comment]
lmao I have no ideas how it can affecting mercury

**Comment by Exslims** [comment]
lmao I have no ideas how it can affecting mercury, but the problem is clearly that something was installed and mercury have stopped working.

**Comment by Exslims** [comment]
found this issue https://bugs.openjdk.java.net/browse/JDK-8178537

**Comment by Exslims** [comment]
guys, who have this issue, please try this version:
[https://github.com/Exslims/MercuryTrade/releases/tag/1.0.1.3a](https://github.com/Exslims/MercuryTrade/releases/tag/1.0.1.3a)

**Comment by DavRo89** [comment]
Hi, i got the same problem with windows 10 and this is the log:

```
2017-04-24 18:08:58.596 [AWT-EventQueue-0] ERROR ErrorHandler - java.lang.InternalError: java.io.FileNotFoundException: \C:\Program Files\Java\jre1.8.0_121\lib\charsets.jar
	at sun.misc.URLClassPath$JarLoader.getResource(Unknown Source)
	at sun.misc.URLClassPath.getResource(Unknown Source)
	at sun.misc.URLClassPath.getResource(Unknown Source)
	at java.lang.ClassLoader.getBootstrapResource(Unknown Source)
	at java.lang.ClassLoader.getResource(Unknown Source)
	at java.lang.ClassLoader.getResource(Unknown Source)
	at java.net.URLClassLoader.getResourceAsStream(Unknown Source)
	at java.util.ResourceBundle$RBClassLoader.getResourceAsStream(Unknown Source)
	at java.util.ResourceBundle$Control$1.run(Unknown Source)
	at java.util.ResourceBundle$Control$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.ResourceBundle$Control.newBundle(Unknown Source)
	at java.util.ResourceBundle.loadBundle(Unknown Source)
	at java.util.ResourceBundle.findBundle(Unknown Source)
	at java.util.ResourceBundle.getBundleImpl(Unknown Source)
	at java.util.ResourceBundle.getBundle(Unknown Source)
	at sun.awt.windows.WMenuItemPeer$2.run(Unknown Source)
	at sun.awt.windows.WMenuItemPeer$2.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.windows.WMenuItemPeer.<clinit>(Unknown Source)
	at sun.awt.windows.WToolkit.createPopupMenu(Unknown Source)
	at java.awt.PopupMenu.addNotify(Unknown Source)
	at java.awt.Component.add(Unknown Source)
	at sun.awt.windows.WTrayIconPeer$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: \C:\Program Files\Java\jre1.8.0_121\lib\charsets.jar
	at sun.misc.URLClassPath$JarLoader.getJarFile(Unknown Source)
	at sun.misc.URLClassPath$JarLoader.access$800(Unknown Source)
	at sun.misc.URLClassPath$JarLoader$1.run(Unknown Source)
	at sun.misc.URLClassPath$JarLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.misc.URLClassPath$JarLoader.ensureOpen(Unknown Source)
	... 43 more

2017-04-24 18:09:00.654 [AWT-EventQueue-0] ERROR ErrorHandler - java.lang.NoClassDefFoundError: Could not initialize class sun.awt.windows.WPopupMenuPeer
	at sun.awt.windows.WToolkit.createPopupMenu(Unknown Source)
	at java.awt.PopupMenu.addNotify(Unknown Source)
	at java.awt.Component.add(Unknown Source)
	at sun.awt.windows.WTrayIconPeer$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

2017-04-24 18:09:00.918 [AWT-EventQueue-0] ERROR ErrorHandler - java.lang.NoClassDefFoundError: Could not initialize class sun.awt.windows.WPopupMenuPeer
	at sun.awt.windows.WToolkit.createPopupMenu(Unknown Source)
	at java.awt.PopupMenu.addNotify(Unknown Source)
	at java.awt.Component.add(Unknown Source)
	at sun.awt.windows.WTrayIconPeer$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

2017-04-24 18:09:01.108 [AWT-EventQueue-0] ERROR ErrorHandler - java.lang.NoClassDefFoundError: Could not initialize class sun.awt.windows.WPopupMenuPeer
	at sun.awt.windows.WToolkit.createPopupMenu(Unknown Source)
	at java.awt.PopupMenu.addNotify(Unknown Source)
	at java.awt.Component.add(Unknown Source)
	at sun.awt.windows.WTrayIconPeer$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by Exslims** [comment]
@DavRo89 please try to re-install java

**Comment by DavRo89** [comment]
Reinstalled java but nothing changed, the log is empty now

**Comment by Exslims** [comment]
@DavRo89 could you try this software, [https://johann.loefflmann.net/en/software/jarfix/index.html](https://johann.loefflmann.net/en/software/jarfix/index.html) some people it helped.

**Comment by DavRo89** [comment]
Tried with the software but nothing changed, i hear the sound but the bar with buttons is not showing

**Comment by Exslims** [comment]
@DavRo89 have you tried alternative laucnher?(with .exe as admin)

**Comment by DavRo89** [comment]
Now with the exe and run as administrator seems to works, thanks for the help

**Comment by Hejtero** [comment]
i don't get why its laggy, sometimes it works ok abut most of the time its laggy and window pop up like 10 sec after the sound alert

**Comment by Exslims** [comment]
@Hejtero its 100% issue with video card software/drivers, may be you have spicific software for your videocard?

**Comment by Hejtero** [comment]
it might be sth with java but dunno, why it started to happen, when it was working great in past :p i will wait for new driver update and maybe then it will fix my problem

**Comment by Hejtero** [comment]
ok seems like the latest Nvidia drivers did fix my problems, will see if it gonna be the same with next update
