### ISSUE TITLE
Failure to launch, loadConfigFile error

### ISSUE THREAD

**Issue by aggixx** [Exslims/MercuryTrade#85]
Seemingly out of nowhere MercuryTrade stopped launching correctly. Here is the error from app.log:

```
2017-05-18 00:42:21.772 [main] ERROR com.mercury.platform.shared.ConfigManager - Error in loadConfigFile: 
org.json.simple.parser.ParseException: null
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257) ~[MercuryTrade.jar:?]
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:92) ~[MercuryTrade.jar:?]
	at com.mercury.platform.shared.ConfigManager.loadConfigFile(ConfigManager.java:177) [MercuryTrade.jar:?]
	at com.mercury.platform.shared.ConfigManager.load(ConfigManager.java:171) [MercuryTrade.jar:?]
	at com.mercury.platform.core.AppStarter.startApplication(AppStarter.java:41) [MercuryTrade.jar:?]
	at com.mercury.platform.AppMain.main(AppMain.java:20) [MercuryTrade.jar:?]
```

Full `app.log`, `app-config.json`, and `configuration.json` files:
[MercuryTrade.zip](https://github.com/Exslims/MercuryTrade/files/1009882/MercuryTrade.zip)

It seems that app-config got corrupted somehow? Dunno. I fixed it by just deleting the two config files but figured it might be of some use to make an issue for it.

**Comment by Exslims** [comment]
At the moment I'm very busy but I recently started to rewrite the configuration code, and possibly may appear such bugs, I'm glad you were able to decide for himself. Thanks for report
