### ISSUE TITLE
Chat scanner and trade helper seems broken in newest build

### ISSUE THREAD

**Issue by thorning** [Exslims/MercuryTrade#98]
I reverted to 1.0.1.5, and it is working there

**Comment by Exslims** [comment]
could you provide app.log file from %userprofile%/appdata/local/MercuryTrade folder

**Comment by thorning** [comment]
```
2017-08-05 18:58:06.849 [Thread-8] ERROR ErrorHandler - java.lang.IllegalArgumentException
	at java.util.Date.parse(Unknown Source)
	at java.util.Date.<init>(Unknown Source)
	at com.mercury.platform.core.utils.MessageFileHandler.lambda$parse$3(MessageFileHandler.java:70)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at com.mercury.platform.core.utils.MessageFileHandler.parse(MessageFileHandler.java:72)
	at com.mercury.platform.core.utils.FileMonitor$1.onFileChange(FileMonitor.java:40)
	at org.apache.commons.io.monitor.FileAlterationObserver.doMatch(FileAlterationObserver.java:410)
	at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:333)
	at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:303)
	at org.apache.commons.io.monitor.FileAlterationMonitor.run(FileAlterationMonitor.java:182)
	at java.lang.Thread.run(Unknown Source)

2017-08-05 20:06:18.327 [nioEventLoopGroup-2-7] ERROR ClientHandler - java.io.IOException: An existing connection was forcibly closed by the remote host
2017-08-06 01:52:59.878 [nioEventLoopGroup-2-3] ERROR ClientHandler - java.io.IOException: An existing connection was forcibly closed by the remote host
2017-08-06 03:53:10.139 [nioEventLoopGroup-2-4] ERROR ClientHandler - java.io.IOException: An existing connection was forcibly closed by the remote host
2017-08-06 05:53:27.077 [nioEventLoopGroup-2-5] ERROR ClientHandler - java.io.IOException: An existing connection was forcibly closed by the remote host
2017-08-06 06:35:01.257 [nioEventLoopGroup-2-6] ERROR ClientHandler - java.io.IOException: An existing connection was forcibly closed by the remote host
2017-08-06 06:36:19.126 [main] ERROR JSONHelper - com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $
2017-08-06 08:46:22.437 [nioEventLoopGroup-2-1] ERROR ClientHandler - java.io.IOException: An existing connection was forcibly closed by the remote host
2017-08-06 10:46:32.858 [nioEventLoopGroup-2-2] ERROR ClientHandler - java.io.IOException: An existing connection was forcibly closed by the remote host
2017-08-06 12:46:43.259 [nioEventLoopGroup-2-3] ERROR ClientHandler - java.io.IOException: An existing connection was forcibly closed by the remote host
2017-08-06 14:46:53.771 [nioEventLoopGroup-2-4] ERROR ClientHandler - java.io.IOException: An existing connection was forcibly closed by the remote host
2017-08-06 16:47:04.466 [nioEventLoopGroup-2-5] ERROR ClientHandler - java.io.IOException: An existing connection was forcibly closed by the remote host
2017-08-06 17:27:36.406 [nioEventLoopGroup-2-6] ERROR ClientHandler - java.io.IOException: An existing connection was forcibly closed by the remote host
2017-08-06 19:36:46.879 [nioEventLoopGroup-2-2] ERROR ClientHandler - java.io.IOException: An existing connection was forcibly closed by the remote host

```

**Comment by Exslims** [comment]
could you send me last 10-15 lines from your log file of the chat(poe folder/logs/Client.txt)

**Comment by thorning** [comment]
Here are some lines around the times above

```
2017/08/05 18:58:02 1384725309 aa6 [DEBUG Client 16728] Got Instance Details from login server
2017/08/05 18:58:02 1384725309 ac6 [INFO Client 16728] Just before calling client instance session
2017/08/05 18:58:02 1384725309 e8 [INFO Client 16728] Connecting to instance server at 146.0.226.111:6112
2017/08/05 18:58:02 1384725355 14c [DEBUG Client 16728] Connect time to instance server was 31ms
2017/08/05 18:58:04 1384727649 981 [INFO Client 16728] : You have entered The Ruined Square.
2017/08/05 18:58:04 1384727789 cab [DEBUG Client 16728] Entering area 1_5_3b
2017/08/05 18:58:06 1384729864 981 [INFO Client 16728] Utula: Cup your hands, children of Kitava.

Drink of the hot, sweet wine of Oriath.

And let us stay ourselves from the feast no longer.

For our king is ravenous!
2017/08/05 18:58:06 1384730129 1fa [DEBUG Client 16728] ClientInternalActor::NotifyOtherClientsAreaLoadComplete - players.size() = 0
2017/08/05 19:00:08 1384851903 aa6 [DEBUG Client 16728] Got Instance Details from login server
2017/08/05 19:00:08 1384851903 ac6 [INFO Client 16728] Just before calling client instance session
2017/08/05 19:00:08 1384851903 e8 [INFO Client 16728] Connecting to instance server at 37.61.219.107:6112
2017/08/05 19:00:08 1384851950 14c [DEBUG Client 16728] Connect time to instance server was 16ms
2017/08/05 19:00:09 1384852746 981 [INFO Client 16728] : You have entered Overseer's Tower.
2017/08/05 19:00:09 1384852808 cab [DEBUG Client 16728] Entering area 1_5_town
```


```
2017/08/06 06:34:48 1426531798 cab [DEBUG Client 10208] Entering area 2_6_town
2017/08/06 06:34:51 1426534793 981 [INFO Client 10208] : You have joined trade chat channel 1 English.
2017/08/06 06:34:51 1426534793 981 [INFO Client 10208] #Sundindo: Well... you're on the right track, I guess
2017/08/06 06:34:52 1426535854 1fa [DEBUG Client 10208] ClientInternalActor::NotifyOtherClientsAreaLoadComplete - players.size() = 1
2017/08/06 06:34:52 1426535854 200 [DEBUG Client 10208] ClientInternalActor::NotifyOtherClientsAreaLoadComplete - Calling ClientAreaLoadComplete() on other client
2017/08/06 06:35:04 1426547539 981 [INFO Client 10208] $LetsGooooooBoi: Wts Max Role Lions Roar 2 EX
2017/08/06 06:35:05 1426548662 981 [INFO Client 10208] $LetsGooooooBoi: Wts Max Role Lions Roar 2 EX
2017/08/06 06:35:14 1426557694 981 [INFO Client 10208] $<OPA> TheTotemBeatle:  lol ^
2017/08/06 06:35:32 1426575993 981 [INFO Client 10208] $Lu_Bu_Bu: ecks dee
2017/08/06 06:35:36 1426579940 981 [INFO Client 10208] $LordGc: WTB Frozen Trail 1c
2017/08/06 06:35:47 1426590361 981 [INFO Client 10208] $<NOCARE> ExcalTemp: WTS
2017/08/06 06:35:49 1426592607 981 [INFO Client 10208] $<‡TPW‡> Zorvroth: WTS _
2017/08/06 06:35:53 1426596617 981 [INFO Client 10208] $Megadon_Dave: WTB Phantasmagoria/Graveyard/Villa/Acid lakes/ ||| 2 alchs each ||| Need atlas progress
2017/08/06 06:35:53 1426596960 981 [INFO Client 10208] $<NOCARE> ExcalTemp: WTB Exalted Orb 38c
2017/08/06 06:35:59 1426602404 981 [INFO Client 10208] $LordGc: WTB Frozen Trail 1c
2017/08/06 06:35:59 1426603137 981 [INFO Client 10208] $<GAEGIS> V_ecx:  wtb _ 1c1alch from a5 quest
2017/08/06 06:36:01 1426604697 981 [INFO Client 10208] $<BEAR> Aule:  WTB The Baron Close Helmet, pm with link
2017/08/06 06:36:03 1426607131 981 [INFO Client 10208] $<GAEGIS> V_ecx:  wtb _ 1c1alch from a5 quest
2017/08/06 06:36:23 1426627130 981 [INFO Client 10208] $<DIRTY"> ThatNegusIsMine: WTB detonate mines
2017/08/06 06:36:37 1426640328 981 [INFO Client 10208] $Megadon_Dave: WTB Phantasmagoria/Graveyard/Villa/Acid lakes/ ||| 2 alchs each ||| Need atlas progress
2017/08/06 06:36:49 1426652808 981 [INFO Client 10208] $Vondyke: WTB chromatics pm ratio
2017/08/06 06:37:10 1426673884 981 [INFO Client 10208] $<OPA> TheTotemBeatle: hey
2017/08/06 06:37:23 1426687066 981 [INFO Client 10208] $<NOOCH> Dizzy_Champion: hey
2017/08/06 06:37:29 1426693072 981 [INFO Client 10208] $<NOCARE> ExcalTemp: WTB Exalted Orb 38c
2017/08/06 06:37:40 1426704226 981 [INFO Client 10208] $chinanambaone: WTSell _ __ 1c each pst
```

**Comment by Exslims** [comment]
in next update try to fix this.

**Comment by Exslims** [comment]
@thorning the problem remained?

**Comment by thorning** [comment]
I have not tried the latest update, will do so tomorrow

**Comment by thorning** [comment]
The newest version did still not work for me.

**Comment by Zangan** [comment]
I'm also having this problem with the latest build.

**Comment by Exslims** [comment]
1. check your poe folder or try alternative launcher
2. try all instructions from troubleshooting page related to this issue
3. this problem is always solved in the second step
